name: malaria
channels:
  - defaults
dependencies:
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - pandas=1.3.5
  - pip=22.3.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - seaborn=0.12.2
